//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngenieriaGD.IGDDemo.App.AndroidApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IngenieriaGD.IGDDemo.App.AndroidApp.ResourceMessages", typeof(ResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must input a address..
        /// </summary>
        internal static string AddressEmpty {
            get {
                return ResourceManager.GetString("AddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must input a anniversary..
        /// </summary>
        internal static string AnniversaryEmpty {
            get {
                return ResourceManager.GetString("AnniversaryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGDDemo App.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument is null..
        /// </summary>
        internal static string ArgumentsNull {
            get {
                return ResourceManager.GetString("ArgumentsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choice a option..
        /// </summary>
        internal static string ChoiceNoSelect {
            get {
                return ResourceManager.GetString("ChoiceNoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must input a client identifier.
        /// </summary>
        internal static string ClientIdEmpty {
            get {
                return ResourceManager.GetString("ClientIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new reading must less or equal than the last reading..
        /// </summary>
        internal static string ClientNewReadingLessThanLastReading {
            get {
                return ResourceManager.GetString("ClientNewReadingLessThanLastReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client read..
        /// </summary>
        internal static string ClientRead {
            get {
                return ResourceManager.GetString("ClientRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must input a new reading and press update..
        /// </summary>
        internal static string ClientReadingEmpty {
            get {
                return ResourceManager.GetString("ClientReadingEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must input a new reading and press update..
        /// </summary>
        internal static string ClientReadingMsg {
            get {
                return ResourceManager.GetString("ClientReadingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client updated..
        /// </summary>
        internal static string ClientUpdated {
            get {
                return ResourceManager.GetString("ClientUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must input a document number..
        /// </summary>
        internal static string DocumentNumberEmpty {
            get {
                return ResourceManager.GetString("DocumentNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t exist item: .
        /// </summary>
        internal static string DoesntExistItem {
            get {
                return ResourceManager.GetString("DoesntExistItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must input a email..
        /// </summary>
        internal static string EmailEmpty {
            get {
                return ResourceManager.GetString("EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must input a first name..
        /// </summary>
        internal static string FirstNameEmpty {
            get {
                return ResourceManager.GetString("FirstNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item can&apos;t update. Please, try again..
        /// </summary>
        internal static string ItemCantUpdate {
            get {
                return ResourceManager.GetString("ItemCantUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item doesn&apos;t exist..
        /// </summary>
        internal static string ItemDoesntExist {
            get {
                return ResourceManager.GetString("ItemDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item found..
        /// </summary>
        internal static string ItemFound {
            get {
                return ResourceManager.GetString("ItemFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item updating....
        /// </summary>
        internal static string ItemUpdating {
            get {
                return ResourceManager.GetString("ItemUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must input a user and password..
        /// </summary>
        internal static string LoginUserOrPasswordEmpty {
            get {
                return ResourceManager.GetString("LoginUserOrPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or password invalid. Please, try again..
        /// </summary>
        internal static string LoginUserOrPasswordInvalid {
            get {
                return ResourceManager.GetString("LoginUserOrPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please waiting. Validating....
        /// </summary>
        internal static string LoginValidating {
            get {
                return ResourceManager.GetString("LoginValidating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must input a phone..
        /// </summary>
        internal static string PhoneEmpty {
            get {
                return ResourceManager.GetString("PhoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request was cancelled..
        /// </summary>
        internal static string RequestCancelled {
            get {
                return ResourceManager.GetString("RequestCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must input a second name..
        /// </summary>
        internal static string SecondNameEmpty {
            get {
                return ResourceManager.GetString("SecondNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please waiting. Searching....
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to IGDDemo App.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
